#!/bin/sh
mkdir -p ~/.luminescence/plugins
for f in "$@" ; do
    echo "installing $(basename "$f" .c)..."
    gcc -g -Wall -shared -o "$HOME/.luminescence/plugins/$(basename "$f" .c).so" "$f" -fPIC `pkg-config --cflags --libs gtk+-3.0 webkitgtk-3.0` $FLAGS
done
